//! Native library boundary.
//!
//! This crate exists to produce the `.so` / `.a` that the Flutter side loads. It
//! holds no logic: everything lives in `photosync-core`, which stays free of
//! platform and FFI concerns (`app_info.md` §17).
//!
//! The real bridge will be generated by `flutter_rust_bridge`. What is here now
//! is the bring-up surface: enough to prove the library links and runs on a
//! device, which is the one thing that cannot be checked on the host.

use std::os::raw::c_int;

/// Result of [`photosync_self_check`].
///
/// Negative values are failures, so a caller can treat `< 0` as "do not
/// continue" without knowing the details.
pub const SELF_CHECK_OK: c_int = 0;
pub const SELF_CHECK_ENGINE_ERROR: c_int = -1;
pub const SELF_CHECK_UNEXPECTED_RESULT: c_int = -2;
pub const SELF_CHECK_PANICKED: c_int = -3;

/// Runs the engine self check (see `photosync_core::bringup`).
///
/// Returns [`SELF_CHECK_OK`] when SQLite linked, migrations applied, and the
/// candidate query behaved as specified. Anything negative means the native
/// library is present but not usable, which is worth failing loudly at start-up
/// rather than discovering mid-sync.
///
/// Panics are caught rather than allowed to cross the FFI boundary, where
/// unwinding is undefined behaviour.
#[no_mangle]
pub extern "C" fn photosync_self_check() -> c_int {
    let outcome = std::panic::catch_unwind(|| match photosync_core::bringup::self_check() {
        Ok(check) if check.is_ok() => SELF_CHECK_OK,
        Ok(_) => SELF_CHECK_UNEXPECTED_RESULT,
        Err(_) => SELF_CHECK_ENGINE_ERROR,
    });
    outcome.unwrap_or(SELF_CHECK_PANICKED)
}

/// Schema version this build understands, for the host side to log.
#[no_mangle]
pub extern "C" fn photosync_schema_version() -> c_int {
    photosync_core::db::SCHEMA_VERSION as c_int
}
